### PR TITLE
User Interface

### PR DESCRIPTION
**Pull request by stansmall**

### CODE REVIEW

**Comment by stansmall** [comment]
https://www.w3schools.com/html/html_form_input_types.asp

**Comment by Selliott452** [comment]
Good start on inputting the document in a web version.  I will continue to work on expanding it.

**Comment by stansmall** [comment]
@Selliott452 This definitely looks a lot better. I'll try to get it up on the server so we can test it on mobile!

**Comment by stansmall** [comment]
looks good

**Pull request merged**
